In [21]:
%run config.ipynb

%run heart_rate.ipynb
%run blood_pressure.ipynb
%run respiration.ipynb

start_point_train = 0
end_point_train = 20

time , hr_train = hr(start_point_train,end_point_train,0,0,0) # print ECG, print resempled, print linear interpulation
time , bp_train = bp(start_point_train,end_point_train,0,0) # print bp, print resempled
time , res_train = res(start_point_train,end_point_train,0,0) # print respiration, print resempled



# Estimated vs Original

1- Finding coefficients vector for each signal
2- X_n+1 = A*X_n


In [24]:
HR_X = hr_sampled_graph[0:len(hr_sampled_graph)-1]    # HR [0..N-1] 
print("HR_X")
print("")
print(HR_X)
print("")
print("HR_X size:", len(HR_X))
print("")

BP_X = sys_sampled_graph[0:len(sys_sampled_graph)-1]    # SYS_BP [0..N-1]
print("BP_X")
print("")
print(BP_X)
print("")
print("BP_X size:", len(BP_X))
print("")

R_X = res_sampled_graph[0:len(res_sampled_graph)-1]    # Resh h [0..N-1]
print("R_X")
print("")
print(R_X)
print("")
print("R_X size:", len(R_X))
print("")



X = np.column_stack((HR_X, BP_X, R_X)) # Mat of all signals in columns from 0 to n-1
print("Matrix X is:")
print(X)
print("")
print("")
print("")



HR_Y = hr_sampled_graph[1:len(hr_sampled_graph)] # taking the hr graph except the first sample
print(HR_Y)
print("HR_Y size:", len(HR_Y))
print()


BP_Y = sys_sampled_graph[1:len(sys_sampled_graph)] # taking the systolic bp graph except the first sample
print(BP_Y)
print("BP_Y size:", len(BP_Y))
print()


R_Y = res_sampled_graph[1:len(res_sampled_graph)] # taking the resp graph except the first sample
print(R_Y)
print("R_Y size:", len(R_Y))
print()



HR_coeff = np.dot(np.linalg.inv(np.dot(X.transpose(),X)),np.dot(X.transpose(),HR_Y))
print("a1,b1,c1 are:")
print(HR_coeff)
print()

BP_coeff = np.dot(np.linalg.inv(np.dot(X.transpose(),X)),np.dot(X.transpose(),BP_Y))
print("a2,b2,c2 are:")
print(BP_coeff)
print()

R_coeff = np.dot(np.linalg.inv(np.dot(X.transpose(),X)),np.dot(X.transpose(),R_Y))
print("a3,b3,c3 are:")
print(R_coeff)
print()


A = np.row_stack((HR_coeff, BP_coeff, R_coeff))
print("The regressed matrix is:")
print("")
print(A)
print("")


HR_X

[134.52914798 134.62449197 134.7160696  ... 134.11433332 134.22260157
 134.32798263]

HR_X size: 1999

BP_X

[1720.         1719.85448674 1719.64185525 ... 1719.9156993  1720.03545515
 1720.09000425]

BP_X size: 1999

R_X

[58.59375    58.60027096 58.60828765 ... 58.5826959  58.5831997
 58.58521135]

R_X size: 1999

Matrix X is:
[[ 134.52914798 1720.           58.59375   ]
 [ 134.62449197 1719.85448674   58.60027096]
 [ 134.7160696  1719.64185525   58.60828765]
 ...
 [ 134.11433332 1719.9156993    58.5826959 ]
 [ 134.22260157 1720.03545515   58.5831997 ]
 [ 134.32798263 1720.09000425   58.58521135]]



[134.62449197 134.7160696  134.8036912  ... 134.22260157 134.32798263
 134.43024005]
HR_Y size: 1999

[1719.85448674 1719.64185525 1719.36242281 ... 1720.03545515 1720.09000425
 1720.07839842]
BP_Y size: 1999

[58.60027096 58.60828765 58.61779507 ... 58.5831997  58.58521135
 58.58872899]
R_Y size: 1999

a1,b1,c1 are:
[ 9.97928922e-01  1.68629397e-04 -1.83894297e-04]

a2,b2,c2 are:
