In [45]:
import numpy as np

#A = np.matrix([0,2,1])
A = np.random.rand(1,3) #    why not working for random matrixes
print("A = ")
print(A)
print(A.shape)
print()
#X = np.matrix( [[1,2,6], [5,10,0], [0,10,10]] )
X = np.random.rand(3,3)
print("X = ")
print(X)
print(X.shape)
print()
Y = np.dot(X,A.transpose())
print("Y = ")
print(Y)
print(Y.shape)
print()
reg_A = np.dot(np.linalg.inv(np.dot(X.transpose(),X)),np.dot(X.transpose(),Y))     # formula for LS method
print("REG_A = ")
print(reg_A)

A = 
[[0.80115748 0.4271676  0.40459125]]
(1, 3)

X = 
[[0.53452836 0.57462745 0.02911208]
 [0.10668117 0.33964829 0.4516096 ]
 [0.2925497  0.42824458 0.52426137]]
(3, 3)

Y = 
[[0.68548212]
 [0.41327245]
 [0.62942215]]
(3, 1)

REG_A = 
[[0.80115748]
 [0.4271676 ]
 [0.40459125]]


In [41]:
A = np.random.rand(1,3)
print("A = ")
print(A)
print()
X = np.random.rand(3,3)
print("X = ")
print(X)
print()
#Y = X*A.transpose()
Y = np.dot(X,A.transpose())
print("Y = ")
print(Y)
print(Y.shape)
print()

A = 
[[0.03144894 0.99636279 0.45253744]]

X = 
[[0.45230497 0.88886099 0.56373229]
 [0.1963022  0.90292198 0.29904974]
 [0.47231662 0.21966695 0.22303796]]

Y = 
[[1.1549625 ]
 [1.04114256]
 [0.33465486]]
(3, 1)

